network:
  port:443
database:
  adapter: mysql
  database: casmrt
  username: toto
  password: ######
  host: localhost
ldap:
  server: localhost
  port: 389
  base: dc=blogdns,dc=org
  filter: (objectClass=*) 
